import React from 'react'
import { Brain } from 'lucide-react'

const AIModelsCard = () => {
  const models = [
    'NLP Classifier',
    'Multimodal Vision', 
    'Risk Scoring (XGBoost)',
    'Repeat Offender (KMeans)'
  ]

  return (
    <div className="bg-cardBg rounded-xl p-6 border border-borderLight shadow-card">
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <Brain className="w-6 h-6 text-accent" />
          <div>
            <h2 className="text-xl font-semibold text-textPrimary">AI Models Powering This Dashboard</h2>
            <p className="text-textSecondary">
              All policies, scores, and actions displayed here are generated by Guardian AI's proprietary machine learning models operating in real time
            </p>
          </div>
        </div>
        
        <div className="flex flex-wrap gap-2">
          {models.map((model, index) => (
            <span 
              key={index}
              className="bg-accent/10 text-accent px-3 py-1 rounded-full text-sm font-medium"
            >
              {model}
            </span>
          ))}
        </div>
      </div>
    </div>
  )
}

export default AIModelsCard